### ISSUE TITLE
Cannot find native modules

### ISSUE THREAD

**Issue by iteloo** [mybuddymichael/linter-elm-make#122]
I'm getting

    I cannot find the module 'Native.<module_name>'

even though running `elm-make` normally doesn't produce such an error. 

I believe it is because `linter-elm-make` is not copying `.js` files in the `Native/` folder to the working directory.

**Comment by halohalospecial** [comment]
Hi @iteloo, do you have `Lint On The Fly` enabled?  Can you try disabling that first?

Right now, `linter-elm-make` is not copying `.js` files from the `Native` directory (if `Lint On The Fly` is enabled or `Work Directory` is set).  Do you have a sample project that we can use for testing so that we can add this?  Thanks!

**Comment by QuinnFreedman** [comment]
I made a PR with a solution for this (https://github.com/mybuddymichael/linter-elm-make/pull/144)

**Comment by halohalospecial** [comment]
Thanks, @QuinnFreedman !
