### ISSUE TITLE
Interfering with elm-make?

### ISSUE THREAD

**Issue by mrmurphy** [mybuddymichael/linter-elm-make#19]
Hi there! This is a strange bug, but I've done my best to put together some reproducible steps:

[the-cheese-palette-elm-only.zip](https://github.com/mybuddymichael/linter-elm-make/files/53051/the-cheese-palette-elm-only.zip)

Above is a zip file with the Elm source from a project I'm working on. I couldn't reproduce the problem in another, stripped down project, so I included this one. Sorry about the mess :)

The following steps _should_ reproduce the error:

1) Run `elm-make admin/Main.elm`, observing that the app compiles successfully
2) Open the unzipped directory in Atom with the linter-elm-make plugin enabled
3) Open Actions.elm and `| Foo` right after line 27, and save
4) Run `elm-make admin/Main.elm` observing that the app compiles successfully, even though it should throw an error, because there's a switch statement inside of Model.elm that now fails to handle the `Foo` case
5) Run `touch admin/Model.elm` and then re-run `elm-make admin/Main.elm`, observing that the compiler now (correctly) errors out
6) Repeat steps 1-3 with the linter-elm-make plugin disabled, and notice that the compiler errors out when it should, without needing to `touch admin/Model.elm`

I hope you're able to reproduce this, and it's not just something maddeningly specific to my setup.
If it's any help, I'm on Atom 1.2, OS X, and Elm 0.16.

---

Also, thanks for writing this package and sharing it with all of us! :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by wmakley** [comment]
Hey, I also have this issue! I have no idea what the fix would be, and my reproduction case is with a godawful huge project as well. As far as I can tell, the linter is making elm-make forget that the file has changed.  Maddening! Especially because it was amazing until it stopped working.

Additionally, in my project, the linter stops picking up the changed code as well, and keeps highlighting things in red that I have fixed long ago.

**Comment by wmakley** [comment]
Incidentally, this is reproducible in the elm package for visual studio code as well. It seems the linter is compiling individual files with elm-make using the same elm-stuff directory as my project, which messes things up when I go to do a final release build. elm-make no longer has a correct idea of what files need to be compiled to build my final .js file for production, because the linter compiled them using the same build-artifacts directory etc. but didn't output the production .js file.

Not sure what the workaround would be other than for the linter to use its own elm-stuff directory, if that's even possible.

**Comment by halohalospecial** [comment]
@wmakley can you try the latest release?  Enabling `Always Compile Main` might resolve your issues.  Also, if `Lint On The Fly` is enabled, the linter will use a temp directory that will have its own `elm-stuff`.  Cheers!

**Comment by halohalospecial** [comment]
@wmakley it's now possible to use a different `elm-stuff` directory by providing a `Work Directory` in the settings.
