### ISSUE TITLE
On-the-fly linting?

### ISSUE THREAD

**Issue by nmn** [mybuddymichael/linter-elm-make#28]
I'm not sure how elm-make handles this, but the linter plugin for sublime text can lint on-the-fly, so I feel Atom should be able to do this too.

It's specially nice when using hot-swapping to know of errors in your code _before_ you save a file.

**Comment by halohalospecial** [comment]
Hi,

I did a proof of concept here: https://github.com/halohalospecial/linter-elm-make/tree/lintonfly (`lintonfly` branch)

Since elm-make requires a file as input, the workaround is to create a temporary file containing the current text in the editor.  I think this is also the approach taken by the Sublime plugin.

Let me know if it works for you.  Cheers!
