### ISSUE TITLE
Always compile Main.elm instead of individual files

### ISSUE THREAD

**Issue by domenkozar** [mybuddymichael/linter-elm-make#32]
I've been hitting a few "cache compilation" issues lately that I _think_ they manifest because of https://github.com/elm-lang/elm-make/issues/72

I suggest `elm-package.json` is inspected for source directories and `Main.elm` is compiled from there. Otherwise saving individual files in Atom can be very unproductive having constant misleading errors or lack of them.

**Comment by domenkozar** [comment]
@splodingsocks thoughts?

**Comment by mrmurphy** [comment]
Great idea, @domenkozar! Thanks for finding that issue. It's really helpful.

I'm on vacation this week, but hopefully will be able to get some time next week to make a branch and try it out.

**Comment by mybuddymichael** [comment]
I kind of wonder if this would fix #19 and #25 as well.

**Comment by halohalospecial** [comment]
I also think this is a good idea @domenkozar.  Though, does this mean that we will not be able to lint modules having no path from main?  (Or is it okay since they are not included in the output anyway?)

Perhaps add a command or setting option to switch between compiling main and compiling the active file?  And maybe another command to clear the build artifacts?  What do you think?

**Comment by halohalospecial** [comment]
PR coming soon =)
