### ISSUE TITLE
Could not find Main.elm in "src"

### ISSUE THREAD

**Issue by joneshf** [mybuddymichael/linter-elm-make#46]
i ran into this a few days ago. When saving, this package will notify me with an error in the top right that disappears within a few seconds, but no stacktrace or action to take. All I get is that line in the title. This is a very confusing error.

It looks like it came from #32. Somehow, this got defaulted to enabled when the package updated. I don't know how, or why. The quick fix is to disable that checkbox in settings if you don't have `Main.elm`.

Perhaps this package could be a bit smarter about `Main.elm` and not die if the checkbox is enabled but `Main.elm` doesn't actually exist?

**Comment by halohalospecial** [comment]
Thank you for reporting this issue, @joneshf!  I checked the source and it did set `Always Compile Main` to `true` as default in a recent update.  Maybe I was testing something and forgot to set it back to `false`.  Sorry about that.

If `Always Compile Main` is enabled, the package will look for `Main.elm` and compile that (i.e. `elm-make Main.elm`).  It really needs `Main.elm` to be present, hence the error when it does not exist.  The alternative is to disable that option, as what you did.  The package will then compile the active file instead.  The rationale for having that option was discussed in https://github.com/mybuddymichael/linter-elm-make/issues/32.

This issue is also timely since right now I'm adding a feature where you can set the main path of your project (not hardcoded to `Main.elm` anymore).  Will release it in a few days.  Thanks!

**Comment by joneshf** [comment]
Thanks for the quick response!

**Comment by halohalospecial** [comment]
Also added useful error details in the latest release.  Thanks again!
