### ISSUE TITLE
Linter will not stop and jumps to the bottom of the file. 

### ISSUE THREAD

**Issue by oakesja** [mybuddymichael/linter-elm-make#54]
With the latest version 0.12.1, the linter continuously lints the file and will not stop. This would be ok except every time that it finishes linting it jumps to the bottom of the file. See the attached GIF for further details.
![elm-linter](https://cloud.githubusercontent.com/assets/2292766/16717300/b2d24cf0-46e1-11e6-9a78-11a96ca31fd0.gif)

**Comment by halohalospecial** [comment]
Hmm, that's so weird!  My hunch is that another package has a bad interaction with `linter-elm-make`.   Maybe a package is saving the file again and again or something.  Can you try renaming your `~/.atom` and restart Atom to start from scratch?  Then just install `language-elm`, `linter`, `linter-elm-make` to see if the issue persists.  Thanks!

**Comment by oakesja** [comment]
Thanks for your response! I tried what you suggested and had no problems with just having `language-elm`, `linter`, and `linter-elm-make` installed. I then reverted everything back to original and disabled the `elm-format` package and the problem went away. Maybe there is a bad interaction between the two package like you suggested?

**Comment by halohalospecial** [comment]
The issue I had with `elm-format` was that the red/yellow squigglies disappear after I save the file.  Not sure in your case if the problem is with `linter-elm-make`+`elm-format` or just with `elm-format`.  Can you try installing just `language-elm` and `elm-format` and see if the problem will occur?  You can also send me your `~/.atom/config.cson` if you want so that I can check your installed packages.  Cheers!

**Comment by oakesja** [comment]
With just `language-elm` and `elm-format` the problem still occurs. Sorry for putting in an issue that isn't even the linter's fault!

**Comment by halohalospecial** [comment]
No worries!  We couldn't be sure before that it's not linter's fault.  At least now we identified the cause. :+1:
